"""Executable acceptance oracle for tenstorrent/tt-metal#51655.

Stdlib-only. This models the issue contract and the pre-fix uint16 behavior
documented in #51655. It does not model Tenstorrent hardware generally and it
does not make a hardware, assignment, or payout claim.

The three FP32 residual bit patterns are taken from the assigned carrier
tenstorrent/tt-metal#53639, which documents them as Blackhole RND_ZERO
exceptions at the reviewed head below.
"""

import json
import math
import struct

TT_METAL_MAIN_SHA = "708e7f58aef9d089f0e5097d4a772c7c8ee129ea"
CARRIER_PR = 53639
CARRIER_HEAD_SHA = "11c41b499c36ea55624226cf0fb3b665cdc0780a"

SOURCE_BLOBS = {
    "blackhole_typecast": "d78ce8c9fa922f7b9491070eb8af393917814458",
    "wormhole_typecast": "bb5a5848dad46bfc5b6b40c27f27cc4362741f26",
    "host_tensor_apis": "c3c678557016af5962ac64f6a3e651b3b8e712cf",
    "sweep_golden": "2b226f32a07cb9d6e51e95dc5a918af5d8c63056",
    "copy_test": "340a330f03043af18c7f951dd240c4a957b801af",
    "llk_golden": "a03adaa505bba87c134434dc1bb58040319bd389",
}

UINT_MAX = {
    "uint8": (1 << 8) - 1,
    "uint16": (1 << 16) - 1,
    "uint32": (1 << 32) - 1,
}
INT32_MIN = -(1 << 31)
INT32_MAX = (1 << 31) - 1

BLACKHOLE_RND_ZERO_RESIDUAL_BITS = (
    0x3F7FFFFE,
    0x3F7FFFFF,
    0x3FFFFFFF,
)


def float32_from_bits(bits):
    return struct.unpack(">f", struct.pack(">I", bits))[0]


def float32_bits(value):
    return struct.unpack(">I", struct.pack(">f", value))[0]


def bfloat16_from_bits(bits):
    return float32_from_bits(bits << 16)


def truncation_contract(value, dtype):
    """Expected issue contract for finite scalar float -> integer conversion."""
    if not math.isfinite(value):
        raise ValueError("oracle only accepts finite inputs")

    truncated = math.trunc(value)
    if dtype in UINT_MAX:
        return max(0, min(UINT_MAX[dtype], truncated))
    if dtype == "int32":
        return max(INT32_MIN, min(INT32_MAX, truncated))
    raise ValueError("unsupported dtype: %s" % dtype)


def legacy_uint16_device(value):
    """Filed uint16 device behavior for ordinary finite inputs.

    #51655 records clamp-to-unsigned followed by nearest/ties-away behavior.
    For non-negative inputs, ties-away is floor(x + 0.5).
    """
    if not math.isfinite(value):
        raise ValueError("oracle only accepts finite inputs")
    return max(0, min(UINT_MAX["uint16"], math.floor(max(value, 0.0) + 0.5)))


def filed_reproducer():
    values = (0.5, 1.5, 2.5, 3.5, 4.5, 0.25, 0.75)
    return {
        dtype: [truncation_contract(value, dtype) for value in values]
        for dtype in ("uint8", "uint16", "uint32", "int32")
    }


def bf16_uint16_legacy_divergences():
    """Return (in_range_count, disagreement_count) over all 65,536 bf16 bits."""
    in_range = 0
    disagreements = 0
    for bits in range(1 << 16):
        value = bfloat16_from_bits(bits)
        if math.isfinite(value) and 0.0 <= value < 65536.0:
            in_range += 1
            if legacy_uint16_device(value) != truncation_contract(value, "uint16"):
                disagreements += 1
    return in_range, disagreements


def carrier_fractional_stimulus_bits():
    """Exact fp32 encodings generated by PR #53639's quarter-step regression."""
    result = set()
    for base in range(63):
        for offset in (0.25, 0.5, 0.75):
            result.add(float32_bits(base + offset))
    return result


def residual_contract_rows():
    stimulus = carrier_fractional_stimulus_bits()
    rows = []
    for bits in BLACKHOLE_RND_ZERO_RESIDUAL_BITS:
        value = float32_from_bits(bits)
        rows.append(
            {
                "bits": "0x%08X" % bits,
                "value": value,
                "expected_trunc": truncation_contract(value, "uint16"),
                "covered_by_carrier_quarter_steps": bits in stimulus,
            }
        )
    return rows


def verify():
    reproducer = filed_reproducer()
    expected = [0, 1, 2, 3, 4, 0, 0]
    assert reproducer == {
        "uint8": expected,
        "uint16": expected,
        "uint32": expected,
        "int32": expected,
    }

    in_range, disagreements = bf16_uint16_legacy_divergences()
    assert in_range == 18305
    assert disagreements == 576

    rows = residual_contract_rows()
    assert [row["expected_trunc"] for row in rows] == [0, 0, 1]
    assert not any(row["covered_by_carrier_quarter_steps"] for row in rows)

    return {
        "tt_metal_main": TT_METAL_MAIN_SHA,
        "carrier_pr": CARRIER_PR,
        "carrier_head": CARRIER_HEAD_SHA,
        "source_blobs": SOURCE_BLOBS,
        "bf16_uint16_in_range": in_range,
        "bf16_uint16_legacy_disagreements": disagreements,
        "blackhole_rnd_zero_residuals": rows,
        "carrier_quarter_step_covers_any_residual": False,
        "status": "PASS",
    }


if __name__ == "__main__":
    print(json.dumps(verify(), indent=2, sort_keys=True))
